/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('ant-design-vue/es')['App']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AIForm: typeof import('./../components/AIForm.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AISettings: typeof import('./../components/AISettings.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableColumn: typeof import('ant-design-vue/es')['TableColumn']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BrowserSettings: typeof import('./../components/BrowserSettings.vue')['default']
    EvaluatorSettings: typeof import('./../components/EvaluatorSettings.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    Login: typeof import('./../views/login.vue')['default']
    Logs: typeof import('./../views/logs.vue')['default']
    NotificationSettings: typeof import('./../components/NotificationSettings.vue')['default']
    NotifierForm: typeof import('./../components/NotifierForm.vue')['default']
    PriceLineChart: typeof import('./../components/PriceLineChart.vue')['default']
    Result: typeof import('./../views/result.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTask: typeof import('./../components/SelectTask.vue')['default']
    System: typeof import('./../views/system.vue')['default']
    TaskForm: typeof import('./../components/TaskForm.vue')['default']
    TaskLogViewer: typeof import('./../views/TaskLogViewer.vue')['default']
    Tasks: typeof import('./../views/tasks.vue')['default']
    TaskSelect: typeof import('./../components/TaskSelect.vue')['default']
    TestTaskSelect: typeof import('./../views/test-task-select.vue')['default']
    Views: typeof import('./../views/index.vue')['default']
  }
}
